cargo-features = ["per-package-target"]

[package]
name = "iocore"
version = "0.1000.1"
edition = "2021"
description = "Indispensable Core Utilities"
documentation = "https://docs.rs/iocore"
readme = "README.md"
homepage = "https://github.com/gabrielfalcao/iocore"
license = "MIT"

[package.metadata]
cargo-args = ["-Zmtime-on-use", "-Zavoid-dev-deps", "-Zcustom_mir"]

[dependencies]
chrono = { version = "0.4.31", features = ["alloc", "serde"] }
glob = "0.3.1"
lazy_static = "1.4.0"
sanitation = { version = "1.0.0" }
serde = { version = "1.0.190", features = ["derive", "alloc", "rc"] }
regex = { version = "1.10.3", features = ["use_std"] }
thread-groups = { version = "0.0.2" }
filetime = "0.2.25"

[dev-dependencies]
clap = { version = "4.5.20", features = ["derive"] }

[lib]
name = "iocore"
path = "iocore/lib.rs"
