[package]
name = "iocore"
version = "0.110.1"
edition = "2021"
description = "Indispensable Core Utilities"
documentation = "https://docs.rs/iocore"
readme = "README.md"
homepage = "https://github.com/github-py/iocore"
exclude = ["tests"]
license = "GPL-3.0-or-later"

[dependencies]
chrono = { version = "0.4.31", features = ["alloc", "serde"] }
glob = "0.3.1"
regex = { version = "1.10.3", features = ["use_std"] }
sanitation = "0.0.0"
serde = { version = "1.0.190", features = ["derive", "alloc", "rc"] }
shellexpand = { version = "3.1.0", features = ["full"] }
walkdir = "2.4.0"

[lib]
name = "iocore"
path = "src/lib.rs"
