[toolchain]
channel = "1.86.0"
components = ["rust-src", "rustc-dev", "rustfmt", "llvm-tools-preview"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "i586-unknown-linux-gnu", "i686-unknown-linux-gnu", "x86_64-pc-windows-msvc", "i686-pc-windows-msvc", "aarch64-pc-windows-msvc", "riscv64gc-unknown-linux-gnu"]