name: ⠗⠥⠎⠞

on:
  push:
    branches:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu_cargo_build:
    name: (Ubuntu) Cargo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release


  macos_cargo_build:
    name: (MacOS) Cargo Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
